### ISSUE TITLE
Label Container Width

### ISSUE THREAD

**Issue by developer-anilpatidar** [prscX/react-native-number-stepper#2]
Can you add Label Container Width same as buttonsContainerWidth so we cad adjust according UI size.

**Comment by prscX** [comment]
@developer-anilpatidar: Please feel free to share a PR for the same.

Thanks
</ Pranav >

**Comment by developer-anilpatidar** [comment]
Sure will do

**Comment by developer-anilpatidar** [comment]
@prscX Already have props width and height so I have just update REDME file.

**Comment by prscX** [comment]
Thanks for the PR.

Thanks
</ Pranav >
